a =input('Digite algo: ')
print('O tipo primitivo desse valor é: ', type(a))
print('Só tem espaços?', a.isspace())
print('É um número?', a.isnumeric())
print('É do alfabeto?', a.isalpha())
print('Tem letras e números?', a.isalnum())
print('Está com maiúsculas?', a.isupper())
print('Está capitalizada?', a.istitle())
